from pywikibot import ItemPage

from wikidata import SITE

CRITIC_REVIEW_QID = "Q80698083"
DEPRECATED_RANK_QID = "Q73737357"
NORMAL_RANK_QID = "Q73737153"
OPENCRITIC_QID = "Q21039459"
OPENCRITIC_TOP_CRITIC_AVERAGE_QID = "Q114712322"
PREFERRED_RANK_QID = "Q71533031"
REDIRECT_QID = "Q45403344"
WITHDRAWN_IDENTIFIER_VALUE_QID = "Q21441764"

CRITIC_REVIEW_ITEM = ItemPage(SITE, CRITIC_REVIEW_QID)
DEPRECATED_RANK_ITEM = ItemPage(SITE, DEPRECATED_RANK_QID)
NORMAL_RANK_ITEM = ItemPage(SITE, NORMAL_RANK_QID)
OPENCRITIC_ITEM = ItemPage(SITE, OPENCRITIC_QID)
OPENCRITIC_TOP_CRITIC_AVERAGE_ITEM = ItemPage(SITE, OPENCRITIC_TOP_CRITIC_AVERAGE_QID)
PREFERRED_RANK_ITEM = ItemPage(SITE, PREFERRED_RANK_QID)
REDIRECT_ITEM = ItemPage(SITE, REDIRECT_QID)
WITHDRAWN_IDENTIFIER_VALUE_ITEM = ItemPage(SITE, WITHDRAWN_IDENTIFIER_VALUE_QID)
