from pywikibot import ItemPage

from wikidata import SITE

DEPRECATED_RANK_QID = "Q73737357"
NORMAL_RANK_QID = "Q73737153"
PREFERRED_RANK_QID = "Q71533031"
REDIRECT_QID = "Q45403344"
WITHDRAWN_IDENTIFIER_VALUE_QID = "Q21441764"

DEPRECATED_RANK_ITEM = ItemPage(SITE, DEPRECATED_RANK_QID)
NORMAL_RANK_ITEM = ItemPage(SITE, NORMAL_RANK_QID)
PREFERRED_RANK_ITEM = ItemPage(SITE, PREFERRED_RANK_QID)
REDIRECT_ITEM = ItemPage(SITE, REDIRECT_QID)
WITHDRAWN_IDENTIFIER_VALUE_ITEM = ItemPage(SITE, WITHDRAWN_IDENTIFIER_VALUE_QID)
