from pywikibot import ItemPage

from wikidata import SITE

REDIRECT_QID = "Q45403344"
WITHDRAWN_IDENTIFIER_VALUE_QID = "Q21441764"

REDIRECT_ITEM = ItemPage(SITE, REDIRECT_QID)
WITHDRAWN_IDENTIFIER_VALUE_ITEM = ItemPage(SITE, WITHDRAWN_IDENTIFIER_VALUE_QID)
