from pywikibot import PropertyPage

from wikidata import SITE

APPLE_TV_EPISODE_ID_PID = "P9750"
APPLE_TV_MOVIE_ID_PID = "P9586"
APPLE_TV_SHOW_ID_PID = "P9751"
DETERMINATION_METHOD_PID = "P459"
IMDB_ID_PID = "P345"
INSTANCE_OF_PID = "P31"
ITUNES_MOVIE_ID_PID = "P6398"
NUMBER_OF_REVIEWS_RATINGS_PID = "P7887"
OPENCRITIC_ID_PID = "P2864"
POINT_IN_TIME_PID = "P585"
REASON_FOR_DEPRECATED_RANK_PID = "P2241"
RETRIEVED_PID = "P813"
REVIEW_SCORE_BY_PID = "P447"
REVIEW_SCORE_PID = "P444"
STATED_IN_PID = "P248"
TMDB_MOVIE_ID_PID = "P4947"

APPLE_TV_EPISODE_ID_PROPERTY = PropertyPage(SITE, APPLE_TV_EPISODE_ID_PID)
APPLE_TV_MOVIE_ID_PROPERTY = PropertyPage(SITE, APPLE_TV_MOVIE_ID_PID)
APPLE_TV_SHOW_ID_PROPERTY = PropertyPage(SITE, APPLE_TV_SHOW_ID_PID)
DETERMINATION_METHOD_PROPERTY = PropertyPage(SITE, DETERMINATION_METHOD_PID)
IMDB_ID_PROPERTY = PropertyPage(SITE, IMDB_ID_PID)
INSTANCE_OF_PROPERTY = PropertyPage(SITE, INSTANCE_OF_PID)
ITUNES_MOVIE_ID_PROPERTY = PropertyPage(SITE, ITUNES_MOVIE_ID_PID)
NUMBER_OF_REVIEWS_RATINGS_PROPERTY = PropertyPage(SITE, NUMBER_OF_REVIEWS_RATINGS_PID)
OPENCRITIC_ID_PROPERTY = PropertyPage(SITE, OPENCRITIC_ID_PID)
POINT_IN_TIME_PROPERTY = PropertyPage(SITE, POINT_IN_TIME_PID)
REASON_FOR_DEPRECATED_RANK_PROPERTY = PropertyPage(SITE, REASON_FOR_DEPRECATED_RANK_PID)
RETRIEVED_PROPERTY = PropertyPage(SITE, RETRIEVED_PID)
REVIEW_SCORE_BY_PROPERTY = PropertyPage(SITE, REVIEW_SCORE_BY_PID)
REVIEW_SCORE_PROPERTY = PropertyPage(SITE, REVIEW_SCORE_PID)
STATED_IN_PROPERTY = PropertyPage(SITE, STATED_IN_PID)
TMDB_MOVIE_ID_PROPERTY = PropertyPage(SITE, TMDB_MOVIE_ID_PID)
