name: Bot

on:
  schedule:
    - cron: "*/30 5,17 * * *"
  workflow_dispatch:

env:
  WIKIDATA_USER_AGENT: "Josh404Bot/${{ github.sha }} (User:Josh404) requests/2.25.1 Python/3.9.4"

jobs:
  tmdb_movie_id:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          QUERY_BATCH_SIZE: 5
        run: |
          python tmdb_movie_id.py | tee output.csv

#     - name: Submit QuickStatements batch
#       env:
#         QUICKSTATEMENTS_USERNAME: Josh404Bot
#         QUICKSTATEMENTS_TOKEN: xxx
#       run: |
#         cat output.csv | python quickstatements.py --batchname TMDbIDs
