name: Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      WIKIDATA_USER_AGENT: "Josh404Bot/1.0 (User:Josh404) requests/2.25.1 Python/3.9.4"
      DRY_RUN: 1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: TMDb movie ID
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          QUERY_BATCH_SIZE: 5
        run: |
          python tmdb_movie_id.py
