name: Daily Reports

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  WIKIDATA_USERNAME: ${{ secrets.WIKIDATA_USERNAME }}

jobs:
  P4947:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          set -o pipefail
          python P4947_report.py | tee report.txt

      - name: Login
        env:
          WIKIDATA_PASSWORD: ${{ secrets.WIKIDATA_PASSWORD }}
        run: |
          python pwb.py login

      - name: Publish report page
        run: |
          python page.py edit --title "User:$WIKIDATA_USERNAME/Maintenance_reports/P4947" <report.txt

  P4983:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          set -o pipefail
          python P4983_report.py | tee report.txt

      - name: Login
        env:
          WIKIDATA_PASSWORD: ${{ secrets.WIKIDATA_PASSWORD }}
        run: |
          python pwb.py login

      - name: Publish report page
        run: |
          python page.py edit --title "User:$WIKIDATA_USERNAME/Maintenance_reports/P4983" <report.txt

  P4985:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          set -o pipefail
          python _report.py | tee report.txt

      - name: Login
        env:
          WIKIDATA_PASSWORD: ${{ secrets.WIKIDATA_PASSWORD }}
        run: |
          python pwb.py login

      - name: Publish report page
        run: |
          python page.py edit --title "User:$WIKIDATA_USERNAME/Maintenance_reports/P4985" <report.txt
