name: Daily Reports

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  WIKIDATA_USERNAME: ${{ secrets.WIKIDATA_USERNAME }}

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        property: ["P9586"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          set -o pipefail
          python report_${{ matrix.property }}.py | tee report.txt

      - name: Login
        env:
          WIKIDATA_PASSWORD: ${{ secrets.WIKIDATA_PASSWORD }}
        run: |
          python pwb.py login

      - name: Publish report page
        run: |
          python page.py edit --title "User:$WIKIDATA_USERNAME/Maintenance_reports/${{ matrix.property }}" <report.txt
