name: Lint Workflows

on:
  push:
    paths: ".github/workflows/**.yml"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Prettier
        run: npm install --global prettier

      - name: Lint with prettier
        run: prettier --check ".github/workflows/*.yml"

  shlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install pyyaml

      - name: Install shfmt
        run: |
          curl --silent https://api.github.com/repos/mvdan/sh/releases/latest |
            jq --raw-output '.assets[] | select(.name| test("shfmt_v.*_linux_amd64")) | .browser_download_url' |
            wget --quiet -O shfmt --input-file=-
          chmod +x shfmt

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: Dump workflow commands to scripts
        id: dump_workflow_scripts
        shell: python
        run: |
          import os

          import yaml

          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
          SHEBANGS = {
              "null": "#!/bin/bash -e",
              "bash": "#!/bin/bash -e\nset -o pipefail",
              "sh": "#!/bin/sh -e",
          }

          input_path = ".github/workflows"
          output_path = os.environ["RUNNER_TEMP"] + "/workflows"

          for workflow_filename in os.listdir(input_path):
              if not workflow_filename.endswith(".yml"):
                  continue

              workflow_id = os.path.basename(workflow_filename).replace(".yml", "")

              with open(f"{input_path}/{workflow_filename}", "r") as f:
                  workflow = yaml.safe_load(f)

              for job_id, job in workflow.get("jobs", []).items():
                  job_dirname = f"{output_path}/{workflow_id}/{job_id}"
                  os.makedirs(job_dirname, exist_ok=True)

                  for idx, step in enumerate(job.get("steps", [])):
                      if "run" not in step:
                          continue

                      shell = step.get("shell", "null")
                      if shell not in SHEBANGS:
                          continue

                      shebang = SHEBANGS[shell]
                      step_id = step.get("id", f"__run_{idx}")
                      name = step.get("name")
                      env = step.get("env")
                      script = step.get("run")

                      filename = f"{job_dirname}/{step_id}.sh"
                      print(filename)

                      with open(filename, "w") as f:
                          f.write(f"{shebang}\n")
                          if name:
                              f.write(f"# name: {name}\n")
                          f.write("\n")
                          if env:
                              for key in env:
                                  f.write(f'export {key}=""\n')
                              f.write("\n")
                          f.write(script)
                          if not script.endswith("\n"):
                              f.write("\n")

      - name: Generate shell file list
        run: |
          find "$RUNNER_TEMP/workflows" -type f -name '*.sh' | tee "$RUNNER_TEMP/shell-files.txt"

      - name: Lint with shfmt
        run: |
          ./shfmt --indent 2 --diff "$RUNNER_TEMP/workflows"

      - name: Lint with ShellCheck
        run: |
          readarray -t files <"$RUNNER_TEMP/shell-files.txt"
          shellcheck "${files[@]}"
