name: Lint Workflows

on:
  push:
    paths: ".github/workflows/**.yml"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Prettier
        run: npm install --global prettier

      - name: Lint with prettier
        run: prettier --check ".github/workflows/*.yml"
