name: Metrics

on:
  workflow_run:
    workflows:
      - "Apple TV ETL"
      - "OpenCritic ETL"
      - "Plex ETL"
      - "TMDB ETL"
      - "Tasks"
    branches: ["main"]
    types: ["completed"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency: metrics

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv pip install --system --requirement requirements.txt

      - name: Make public directory
        run: |
          mkdir -p public/

      - name: Run script
        run: |
          python metrics.py >public/metrics.prom

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
