name: Metrics

on:
  workflow_run:
    workflows:
      - "Apple TV ETL"
      - "OpenCritic ETL"
      - "Plex ETL"
      - "TMDB ETL"
      - "Tasks"
    branches: ["main"]
    types: ["completed"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency: metrics

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python metrics.py >metrics.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: github.ref == 'refs/heads/main'
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Upload to S3
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp --acl public-read "metrics.txt" "s3://wikidatabots/metrics"
