name: Plex ETL

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  WIKIDATA_USERNAME: ${{ secrets.WIKIDATA_USERNAME }}

jobs:
  discover_guids:
    runs-on: ubuntu-latest
    concurrency: plex
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Python path
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >>"$GITHUB_ENV"

      - name: Download from S3
        run: |
          aws s3 cp "s3://wikidatabots/plex.arrow" "plex.arrow"
          cp plex.arrow plex.arrow~

      - name: Run script
        shell: python
        run: |
          from plex_etl import main_discover_guids

          main_discover_guids()
        env:
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
          PLEX_SERVER: ${{ secrets.PLEX_SERVER }}

      - name: Print stats
        run: |
          python print_table_stats.py plex.arrow

      - name: Print diff
        run: |
          python print_table_diff.py plex.arrow~ plex.arrow key

      - name: Upload to S3
        run: |
          aws s3 cp --acl public-read "plex.arrow" "s3://wikidatabots/plex.arrow"

  metadata:
    needs: [discover_guids]
    runs-on: ubuntu-latest
    concurrency: plex
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Python path
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >>"$GITHUB_ENV"

      - name: Download from S3
        run: |
          aws s3 cp "s3://wikidatabots/plex.arrow" "plex.arrow"
          cp plex.arrow plex.arrow~

      - name: Backfill missing metadata
        shell: python
        run: |
          from plex_etl import main_metadata

          main_metadata()
        env:
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}

      - name: Print stats
        run: |
          python print_table_stats.py plex.arrow

      - name: Print diff
        run: |
          python print_table_diff.py plex.arrow~ plex.arrow key

      - name: Upload to S3
        run: |
          aws s3 cp --acl public-read "plex.arrow" "s3://wikidatabots/plex.arrow"
