name: Plex ETL

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  WIKIDATA_USERNAME: ${{ secrets.WIKIDATA_USERNAME }}

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency: plex
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download from S3
        run: |
          aws s3 cp "s3://wikidatabots/plex.parquet" "plex.parquet"
          cp plex.parquet plex.parquet~

      - name: Run script
        run: |
          python plex_etl.py
        env:
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
          PLEX_SERVER: ${{ secrets.PLEX_SERVER }}

      - name: Print stats
        run: |
          python print_table_stats.py plex.parquet | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Print diff
        run: |
          python print_table_diff.py plex.parquet~ plex.parquet key | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Upload to S3
        run: |
          aws s3 cp --acl public-read "plex.parquet" "s3://wikidatabots/plex.parquet"
