name: Plex ETL

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  wikidata:
    runs-on: ubuntu-latest
    concurrency: plex
    if: github.event.schedule == '0 15 * * *' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Python path
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >>"$GITHUB_ENV"

      - name: Download from S3
        run: |
          aws s3 cp "s3://wikidatabots/plex.arrow" "plex.arrow"
          cp plex.arrow plex.arrow~

      - name: Fetch Wikidata Plex GUIDs
        shell: python
        run: |
          import pandas as pd

          from pandas_utils import df_append_new
          from plex_etl import wd_plex_guids

          df = pd.read_feather("plex.arrow")
          df_wd = wd_plex_guids()
          df = df_append_new(df, df_wd, on="guid").sort_values("guid")
          df.to_feather("plex.arrow")

      - name: Print stats
        run: |
          python print_table_stats.py plex.arrow

      - name: Print diff
        run: |
          python print_table_diff.py plex.arrow~ plex.arrow guid

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plex
          path: |
            *.arrow
          retention-days: 7

      - name: Upload to S3
        run: |
          aws s3 cp "plex.arrow" "s3://wikidatabots/plex.arrow"
