name: Plex ETL

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-24.04
    concurrency: plex

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync

      - name: Download from S3
        run: |
          aws s3 cp --region us-east-1 --no-sign-request "s3://wikidatabots/plex.parquet" "plex.parquet"

      - name: Run script
        run: |
          uv run plex_etl.py
        env:
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
          PLEX_SERVER: ${{ secrets.PLEX_SERVER }}
          WIKIDATA_USERNAME: ${{ secrets.WIKIDATA_USERNAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: github.ref == 'refs/heads/main'
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Upload to S3
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp --acl public-read "plex.parquet" "s3://wikidatabots/plex.parquet"
