name: TMDB ETL

on:
  schedule:
    - cron: "0 0,8,16 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency: tmdb_${{ matrix.type }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
          - type: "movie"
          - type: "tv"
          - type: "person"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Python path
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >>"$GITHUB_ENV"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Download from S3
        run: |
          aws s3 cp "s3://wikidatabots/tmdb/${TYPE}.arrow" "tmdb.arrow"
          aws s3 cp "s3://wikidatabots/tmdb/${TYPE}/latest_changes.arrow" "latest_changes.arrow"
          aws s3 cp "s3://wikidatabots/tmdb/${TYPE}/external_ids.arrow" "external_ids.arrow"
          cp tmdb.arrow tmdb.arrow~
          cp latest_changes.arrow latest_changes.arrow~
          cp external_ids.arrow external_ids.arrow~
        env:
          TYPE: ${{ matrix.type }}

      - name: Run ETL script
        run: |
          python tmdb_etl.py "$TYPE"
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TYPE: ${{ matrix.type }}

      - name: Print stats
        run: |
          python print_table_stats.py tmdb.arrow

      - name: Print diff
        run: |
          python print_table_diff.py tmdb.arrow~ tmdb.arrow id

      - name: Upload to S3
        run: |
          aws s3 cp "tmdb.arrow" "s3://wikidatabots/tmdb/${TYPE}.arrow"
          aws s3 cp "latest_changes.arrow" "s3://wikidatabots/tmdb/${TYPE}/latest_changes.arrow"
          aws s3 cp "external_ids.arrow" "s3://wikidatabots/tmdb/${TYPE}/external_ids.arrow"
        env:
          TYPE: ${{ matrix.type }}
