name: TMDB ETL

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency: tmdb_${{ matrix.type }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - type: "movie"
          - type: "tv"
          - type: "person"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: |
          uv pip install --system --requirement requirements.txt
      - name: Download from S3
        run: |
          aws s3 cp --region us-east-1 --no-sign-request "s3://wikidatabots/tmdb/${TYPE}.parquet" "tmdb.parquet"
        env:
          TYPE: ${{ matrix.type }}

      - name: Run ETL script
        run: |
          python tmdb_etl.py "$TYPE"
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TYPE: ${{ matrix.type }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: github.ref == 'refs/heads/main'
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Upload to S3
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp --acl public-read "tmdb.parquet" "s3://wikidatabots/tmdb/${TYPE}.parquet"
        env:
          TYPE: ${{ matrix.type }}
