name: TMDB

on:
  push:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        type:
          - "movie"
          - "tv"
          - "person"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Run script
        run: |
          python tmdb_index.py ${{ matrix.type }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.type }}-feather
          path: |
            *.feather
