name: Weekly Tasks

on:
  schedule:
    - cron: "0 16 * * 1"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  WIKIDATA_USERNAME: ${{ secrets.WIKIDATA_USERNAME }}

jobs:
  not_found_tmdb:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - tmdb_type: "movie"
          - tmdb_type: "tv"
          - tmdb_type: "person"

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        shell: bash
        run: |
          python not_found_tmdb.py "$TMDB_TYPE" | tee not_found_tmdb.ttl
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_TYPE: ${{ matrix.tmdb_type }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: not_found_tmdb_${{ matrix.tmdb_type }}_ttl
          path: |
            *.ttl
          retention-days: 7

  rdf_patch:
    needs: not_found_tmdb
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Combine artifacts
        run: find artifacts/ -name not_found_tmdb.ttl -exec cat {} \; | tee not_found_tmdb.ttl

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login
        env:
          WIKIDATA_PASSWORD: ${{ secrets.WIKIDATA_PASSWORD }}
        run: |
          python pwb.py login

      - name: Process RDF statements
        run: |
          python rdf_patch.py <not_found_tmdb.ttl
