name: Weekly Tasks

on:
  schedule:
    - cron: "0 16 * * 1"
  workflow_dispatch:

jobs:
  not_found_tmdb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        shell: bash
        run: |
          python not_found_tmdb.py | tee statements.ttl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
