name: Wikidata ETL

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Download from S3
        run: |
          aws s3 cp "s3://wikidatabots/wikidata/property_class_constraints.arrow" "property_class_constraints.arrow~"

      - name: Run ETL script
        run: |
          python wikidata_etl.py

      - name: Print stats
        run: |
          python print_table_stats.py property_class_constraints.arrow

      - name: Print diff
        run: |
          python print_table_diff.py property_class_constraints.arrow~ property_class_constraints.arrow class_numeric_qid

      - name: Upload to S3
        run: |
          aws s3 cp "property_class_constraints.arrow" "s3://wikidatabots/wikidata/property_class_constraints.arrow"
