name: Wikidata ETL

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  WIKIDATA_USERNAME: ${{ secrets.WIKIDATA_USERNAME }}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Download from S3
        run: |
          aws s3 cp "s3://wikidatabots/wikidata/property_class_constraints.parquet" property_class_constraints.parquet

      - name: Run ETL script
        run: |
          python wikidata_etl.py

      - name: Upload to S3
        run: |
          aws s3 cp --acl public-read "property_class_constraints.parquet" "s3://wikidatabots/wikidata/property_class_constraints.parquet"
